title: CristyNel
# available at: https://cristynel.github.io/CristyNel/

#* directly from github with no Domains
# url: "https://cristynel.github.io"
# baseurl: "/CristyNel"

#* with old custom domain
# url: "https://cristinelnelubuliga.online"
# baseurl: ""

#* with new custom domain
url: "https://cristinel.store"
baseurl: ""

# Site settings
email: buligacristinelnelly@gmail.com
description: "Passionate full-stack software engineer based in London. Enjoy creating web applications and games. Studying Computer Science at the University of Suffolk. Love traveling, hiking, reading the Bible, and learning new languages."

# Team names, titles and social links
people:
  - name: Cristinel Nelu
    pic: 1
    position: "Full Stack Developer"
    social:
      - title: linkedn
        url: "https://www.linkedin.com/in/buliga-cristinel-nelu/"
      - title: youtube
        url: "https://www.youtube.com/@buligacristinel-nelu2740"
      - title: github
        url: "https://github.com/CristyNel"
      - title: envelope
        url: "mailto:buligacristinelnelly@gmail.com"

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: "https://www.linkedin.com/in/buliga-cristinel-nelu/"
  - title: youtube
    url: "https://www.youtube.com/@buligacristinel-nelu2740"
  - title: github
    url: "https://github.com/CristyNel"
  - title: envelope
    url: "mailto:buligacristinelnelly@gmail.com"

  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# https://cristinelnelubuliga.online"

# Postal address (add as many lines as necessary)
address:
  - line: London
  - line: England (United Kingdom)

# Build settings
markdown: kramdown
permalink: pretty
